Add a msg for create PeriodicVestingAccount
agoric-labs/cosmos-sdk pull request #54
Opened 2021-05-23 04:42 UTC by zmanian

Pull Request of the periodic vesting msg

## Description

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2021-05-26 01:06 UTC, JimLarson requested changes

2021-05-26 01:06 UTC, JimLarson commented on proto/cosmos/vesting/v1beta1/tx.proto
> +}
Add newline at end of file.

2021-05-26 01:06 UTC, JimLarson commented on proto/cosmos/vesting/v1beta1/tx.proto
> +  repeated Period vesting_periods = 3 [(gogoproto.nullable) = false];
Specify (here or elsewhere) the semantics of the periods: is a period automatically repeating?  If I want to vest 25 quatloos per year over 4 years, do I need one Period field here, or 4?

2021-05-26 01:06 UTC, JimLarson commented on x/auth/vesting/client/cli/tx.go
> +		Long: `Create a new vesting account funded with an allocation of tokens. This takes a destingation address and
Change `destingation` to `destination`.

2021-05-26 01:06 UTC, JimLarson commented on x/auth/vesting/handler_test.go
> +		},
Consider adding TODO comments for additional tests, invalid address, empty periods file, etc.

2021-05-26 01:06 UTC, JimLarson commented on x/auth/vesting/client/cli/tx.go
> +				period := types.Period{Length: p.Time, Amount: amount}
There seems to be a mismatch between `p.Time` which is, as far as I can tell, a UNIX epoch timestamp, and the `Length` field, which `vesting.proto` implies is a duration, and is used in the context of a `start_time` field. It sure looks like this code puts a timestamp value into a duration field. If that's not the case, then either some variables or fields should be renamed, or a big comment added.

2021-06-04 05:46 UTC, zmanian commented on proto/cosmos/vesting/v1beta1/tx.proto
> +  repeated Period vesting_periods = 3 [(gogoproto.nullable) = false];
You need 4 vesting periods of 31536000 seconds.

2021-06-04 05:46 UTC, zmanian commented on proto/cosmos/vesting/v1beta1/tx.proto
> +  repeated Period vesting_periods = 3 [(gogoproto.nullable) = false];
Periods are incremental and sequential.

2021-06-04 05:50 UTC, zmanian commented
Pushed changes to address comments.

2021-06-15 00:58 UTC, JimLarson requested changes
Thanks for the explanation! Since there are other reasonable ways to implement periods that all use int in the spec, I've suggested some good places for comments. It would also be good to raise an error on zero or negative period length.

2021-06-15 00:58 UTC, JimLarson commented on x/auth/vesting/client/cli/tx.go
> +		An array of coin strings and unix epoch times for coins to vest
Change description to "A sequence of coins and period length in seconds. Periods are sequential, in that the duration of of a period only starts at the end of the previous period. The duration of the first period starts upon account creation. For instance, the following periods.json file shows 40 "test" coins vesting annually over 4 years, where the 3rd year is a leap year." ... followed by the appropriate example.

I could imagine periods specified by the ending timestamp, or by duration from the creation of the account, so the particular choice needs to be stated more clearly, especially in external interfaces.

2021-06-15 00:58 UTC, JimLarson commented on x/auth/vesting/client/cli/tx.go
> +  "length_seconds":1620016673
Change to a more reasonable vesting length, here and below.

2021-06-15 00:58 UTC, JimLarson commented on proto/cosmos/vesting/v1beta1/tx.proto
> +  repeated Period vesting_periods = 3 [(gogoproto.nullable) = false];
Okay, that checks out in the code. There's at least two other obvious ways to implement periods that use the same types (timestamp and duration-from-account-creation), so this particular choice needs to be clearly stated through all the interfaces.

Note that I don't see any prohibition of zero or negative duration, either in comments or validation checks.

2021-06-15 00:58 UTC, JimLarson commented on x/auth/vesting/client/cli/tx.go
> +				period := types.Period{Length: p.Length, Amount: amount}
Error on zero or negative length?

2021-06-15 00:58 UTC, JimLarson commented on x/auth/vesting/handler_test.go
> +		},
Also for zero or negative period length.

2021-06-15 00:58 UTC, JimLarson commented on x/auth/vesting/types/msgs.go
> +func (msg MsgCreatePeriodicVestingAccount) ValidateBasic() error {
This might be a good place to check for zero or negative period lengths.

2021-06-21 04:27 UTC, zmanian commented on proto/cosmos/vesting/v1beta1/tx.proto
> +  repeated Period vesting_periods = 3 [(gogoproto.nullable) = false];
Add length checks to in ValidateBasic

2021-06-21 04:42 UTC, zmanian commented
Resolved the major outstanding issues.

2021-06-21 06:36 UTC, JimLarson approved these changes

2021-06-21 15:13 UTC, merged